### ISSUE TITLE
Add README

### ISSUE THREAD

**Issue by sskorol** [pyjamasam/snips-respeakerd#2]
Hi @pyjamasam,

Thanks for sharing this project. Could you please add a README with setup/build instructions and some architecture diagram?

**Comment by pyjamasam** [comment]
Sadly this project is all but dead.  Snips is gone, and I have no use for this code any more.  Build instructions should be a simple "make" as long as the required libraries are installed (librespeakerd, mosquitto, and maybe a few others that I can't remember).

This application was to take the place of the snips-audio-server (at least on the recording side) and allow the use of other librespeaker hotword systems, as well as support the DOA and other advanced audio processing the respeaker mic array provided.

I am not using this code any more, and I have no intention of doing anything else with it.  I think I am going to archive the project just so it sticks around as a reference to how to interact with the respeakersdk
